version: "3.7"
services:
    mongo:
        build: ./packages/shark7-mongo
        restart: unless-stopped
        container_name: shark7-mongo
        volumes:
            - mongodata:/data/db
            - ./backup:/backup
        networks:
            - default
        ports:
            - "127.0.0.1:27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=shark7
    mongo-init:
        image: mongo
        container_name: shark7-mongo-init
        networks:
            - default
        depends_on:
            - mongo
        command:
            - mongo
            - mongodb://admin:shark7@mongo:27017/admin
            - --eval
            - 'rs.initiate({ _id: "rs0", members: [{_id:1,host:"mongo:27017"}]})'
    weibo:
        build: ./packages/shark7-weibo
        volumes:
            - ./packages/shark7-weibo/data:/app/data
        container_name: shark7-weibo
        depends_on:
            - mongo
        networks:
            - default
        environment:
            # - NODE_ENV=development
            - MONGODB_PASS=shark7
            - MONGODB_IP=mongo
            - weibo_id=123456
    apex:
        build: ./packages/shark7-apex
        container_name: shark7-apex
        depends_on:
            - mongo
        networks:
            - default
        environment:
            # - NODE_ENV=development
            - MONGODB_PASS=shark7
            - MONGODB_IP=mongo
            - apex_uid=DisplayName:1001234567890
    main:
        build: ./packages/shark7-main
        container_name: shark7-main
        depends_on:
            - mongo
        networks:
            - default
        environment:
            # - NODE_ENV=development
            - MONGODB_PASS=shark7
            - MONGODB_IP=mongo
            - khl_token=aaaabbbbb
            - khl_msg_channel_id=123456,234567
            - khl_log_channel_id=123456
    # shark7:
    #     build: ./
    #     volumes:
    #         - ./data:/app/data
    #     container_name: shark7
    #     # cap_add:
    #     #     - SYS_ADMIN
    #     restart: unless-stopped
volumes:
    mongodata:

networks:
    default:
        driver: bridge
