version: "3.7"
services:
    shark7-mongo:
        build: ./packages/shark7-mongo
        restart: unless-stopped
        container_name: shark7-mongo
        volumes:
            - mongodata:/data/db
            - ./backup:/backup
        networks:
            - default
        ports:
            - "127.0.0.1:27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
    shark7-mongo-init:
        image: mongo
        container_name: shark7-mongo-init
        networks:
            - default
        depends_on:
            - shark7-mongo
        command:
            - mongo
            - mongodb://admin:admin@shark7-mongo:27017/admin
            - --eval
            - 'sleep(5000);rs.initiate({ _id: "rs0", members: [{_id:1,host:"shark7-mongo:27017"}]})'
    shark7-weibo:
        build:
            context: .
            dockerfile: ./packages/shark7-weibo/Dockerfile
        volumes:
            - ./packages/shark7-weibo/data:/app/data
        container_name: shark7-weibo
        depends_on:
            - shark7-mongo
        networks:
            - default
        security_opt:
            - seccomp=./chrome_seccomp.json
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=admin
            - MONGODB_IP=shark7-mongo
            - weibo_id=
    shark7-apex:
        build:
            context: .
            dockerfile: ./packages/shark7-apex/Dockerfile
        container_name: shark7-apex
        depends_on:
            - shark7-mongo
        networks:
            - default
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=admin
            - MONGODB_IP=shark7-mongo
            - apex_uid=YourUserName:10012345678
    shark7-bililive:
        build:
            context: .
            dockerfile: ./packages/shark7-bililive/Dockerfile
        container_name: shark7-bililive
        depends_on:
            - shark7-mongo
        networks:
            - default
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=admin
            - MONGODB_IP=shark7-mongo
            - room_id=
            - marked_uid=
    shark7-bililive-guard:
        build:
            context: .
            dockerfile: ./packages/shark7-bililive-guard/Dockerfile
        container_name: shark7-bililive-guard
        depends_on:
            - shark7-mongo
        networks:
            - default
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=admin
            - MONGODB_IP=shark7-mongo
            - room_id=
            - marked_uid=
    shark7-main:
        build:
            context: .
            dockerfile: ./packages/shark7-main/Dockerfile
        container_name: shark7-main
        depends_on:
            - shark7-mongo
        networks:
            - default
        environment:
            - NODE_ENV=production
            - MONGODB_PASS=admin
            - MONGODB_IP=shark7-mongo
            - khl_token=
            - 'khl_channels=[{"id":"1234","exclude":[{"scope":"Apex"}]},{"id":"5678","include":[{"scope":"BiliLive.Danmaku"}]}]'

volumes:
    mongodata:


networks:
    default:
        driver: bridge
