name: "Shark7 mongo Build"

on:
  push:
    branches:
      - v2
      - dev
    paths:
      - "packages/shark7-mongo/**"
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build
        run: docker build -t acedroidx/shark7-mongo:${GITHUB_REF##*/} ./packages/shark7-mongo/
      - name: Log In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: docker push acedroidx/shark7-mongo:${GITHUB_REF##*/}
